spring:
  datasource:
    master:
      password: test
      url: jdbc:mysql://127.0.0.1:3306/dacker_master?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      type: com.zaxxer.hikari.HikariDataSource
      testOnBorrow: true
      validationQuery: select 1 from dual
    cluster:
    - key: slave1
      password: test
      url: jdbc:mysql://127.0.0.1:3306/dacker_slave1?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
      idle-timeout: 20000
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      type: com.zaxxer.hikari.HikariDataSource
    - key: slave2
      password: test
      url: jdbc:mysql://127.0.0.1:3306/dacker_slave2?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.jdbc.Driver
      username: root

#redis集群配置
#    Redis集群部署 - 密码暂无 12个节点
#集群版
  redis:
      cluster:
        nodes:
          - 192.168.0.162:7001
          - 192.168.0.162:7002
          - 192.168.0.162:7003
          - 192.168.0.162:7004
          - 192.168.0.162:7005
          - 192.168.0.162:7006
          - 192.168.0.163:7001
          - 192.168.0.163:7002
          - 192.168.0.163:7003
          - 192.168.0.163:7004
          - 192.168.0.163:7005
          - 192.168.0.163:7006
        max-redirects: 3  # 获取失败 最大重定向次数
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10    # 连接池中的最大空闲连接
        max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle:  5     # 连接池中的最小空闲连接
      timeout: 6000  # 连接超时时长（毫秒）